# Generated by Django 6.0.6 on 2026-06-15 19:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extrusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basket', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Invalid basket number.', regex='^\\d{,4}$')])),
                ('card_no', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Invalid card number', regex='^\\d{8}$')])),
                ('card_grm', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='GRM must be greater than zero.')])),
                ('k_route', models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=6, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='master_data.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
