# Generated by Django 6.0.6 on 2026-06-17 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrusion',
            name='card_no',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid card number', regex='^\\d{8}$')]),
        ),
    ]
