# Generated by Django 6.0.6 on 2026-06-15 19:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extrusion', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'planned'), ('draft', 'draft'), ('complete', 'complete')], default='draft', max_length=15)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='master_data.reference')),
            ],
            options={
                'ordering': ['-date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'), message='Measured length must be greater than zero.')])),
                ('workpiece_weight_gr', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'), message='Weight must be greater than zero.')])),
                ('machined_weight_gr', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'), message='Weight must be greater than zero.')])),
                ('measured_gpm', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True)),
                ('k_vs_basket', models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=6, null=True)),
                ('k_vs_theoretical', models.DecimalField(blank=True, decimal_places=5, editable=False, max_digits=6, null=True)),
                ('workpiece_delta_pct', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=6, null=True)),
                ('reference_delta_pct', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=6, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.batch')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='extrusion.extrusion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
