# Generated by Django 6.0.6 on 2026-06-15 19:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=40)),
                ('theoretical_gpm', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'), message='Theoretical grams per meter must be greater than zero.')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Please enter a valid material number.', regex='^[12]\\d{7}$')])),
                ('description', models.CharField(max_length=40)),
                ('theoretical_weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Theoretical net weight must be greater than zero.')])),
                ('nominal_length_mm', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'), message='Nominal length must be greater than zero.')])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpieces', to='master_data.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Please enter a valid material number.', regex='^[12]\\d{7}$')])),
                ('description', models.CharField(max_length=40)),
                ('theoretical_weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Theoretical net weight must be greater than zero.')])),
                ('customer_number', models.CharField(blank=True, max_length=40, null=True)),
                ('workpiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='master_data.workpiece')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
