# Generated by Django 6.0.6 on 2026-06-17 19:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theoretical_gpm',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'), message='Theoretical grams per meter must be greater than zero.')]),
        ),
        migrations.AlterField(
            model_name='reference',
            name='material',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid material number.', regex='^[12]\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='workpiece',
            name='material',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid material number.', regex='^[12]\\d{7}$')]),
        ),
    ]
